### ISSUE TITLE
Port conflict when another process is occupying :5000

### ISSUE THREAD

**Issue by Pittconnect** [WRI-Cities/static-GTFS-manager#87]
https://paste.ubuntu.com/p/F6z6zksPXt/

Windows 10,
Installed

**Comment by answerquest** [comment]
This happened because the program was trying for port 5000 only which was occupied by another process in OP's case. Brought in a while-try-except loop to try next port number if one is found occupied.

https://github.com/WRI-Cities/static-GTFS-manager/blob/02aceecc8ec7a00564a0c50833c34aee59b2c3c4/GTFSManager.py#L1278

fixed in v2.0.0
